### PR TITLE
Fix compilation with GCC 4.8/4.9

### LINKED ISSUE #1377: Compilation failure with json_parsing.cpp post 6d0e2b7
Hi,
Cpprest build fails with the below errors,

src/json/json_parsing.cpp:1077:20: error: could not convert ‘value’ from ‘std::unique_ptr<web::json::details::_String, std::default_delete<web::json::details::_String> >’ to ‘std::unique_ptr<web::json::details::_Value>’
             return value;
                    ^
Release/src/json/json_parsing.cpp:1089:20: error: could not convert ‘value’ from ‘std::unique_ptr<web::json::details::_Number, std::default_delete<web::json::details::_Number> >’ to ‘std::unique_ptr<web::json::details::_Value>’
             return value;
                    ^
src/json/json_parsing.cpp:1096:20: error: could not convert ‘value’ from ‘std::unique_ptr<web::json::details::_Number, std::default_delete<web::json::details::_Number> >’ to ‘std::unique_ptr<web::json::details::_Value>’
             return value;
                    ^
Release/src/json/json_parsing.cpp:1103:20: error: could not convert ‘value’ from ‘std::unique_ptr<web::json::details::_Boolean, std::default_delete<web::json::details::_Boolean> >’ to ‘std::unique_ptr<web::json::details::_Value>’
             return value;
                    ^

Release/src/json/json_parsing.cpp:1043:28:error: could not convert ‘result’ from ‘std::unique_ptr<web::json::details::_Array, std::default_delete<web::json::details::_Array> >’ to ‘std::unique_ptr<web::json::details::_Value>’
                     return result;

I am on gcc 4.8 and boost_1_68.

This has not been observed in the earlier commit cdae258.

Am I missing something during the build?

Thanks & Regards,
Swathi Desai

### PR DESCRIPTION
**Pull request by garethsb-sony**
Sorry, I broke them in commit 53fab3aa124eb712c0d5c4861438ecdbc5b5c2d5.
Should resolve #1377, based on https://godbolt.org/z/whpF2e.

### CODE REVIEW

**Comment by garethsb-sony** [comment]
Confirmed to resolve the issue by @swathidesai.
@BillyONeal please would you review?

**Comment by BillyONeal** [comment]
I'm not super enthusiastic about this given that we don't have a way to prevent regressions but it doesn't seem harmful. Assuming we get OK tests back will merge.

**Comment by jweekshell** [comment]
We would really like to see this patch!
