### PR TITLE
fix format-truncation on 64bit

### LINKED ISSUE #1461: Can't compile on GCC 10.1
building on `gcc 10.1` with a reasonable warning set breaks the build.
Same code on `gcc 9.x` builds fine
`
| /work/src/http/common/http_helpers.cpp:91:43: error: '%8zX' directive output may be truncated writing between 8 and 16 bytes into a region of size 9 [-Werror=format-truncation=]
|    91 |         snprintf(buffer, sizeof(buffer), "%8zX", bytes_read);
|       |                                           ^~~~
| /work/src/http/common/http_helpers.cpp:91:42: note: directive argument in the range [1, 18446744073709551615]
|    91 |         snprintf(buffer, sizeof(buffer), "%8zX", bytes_read);
|       |                                          ^~~~~~
| In file included from /include/usr/include/stdio.h:867,
|                  from /include/usr/include/c++/10.1.0/cstdio:42,
|                  from /include/usr/include/c++/10.1.0/ext/string_conversions.h:43,
|                  from /include/usr/include/c++/10.1.0/bits/basic_string.h:6535,
|                  from /include/usr/include/c++/10.1.0/string:55,
|                  from /work/src/pch/stdafx.h:52,
|                  from /work/src/http/common/http_helpers.cpp:14:
| /include/usr/include/bits/stdio2.h:67:35: note: '__builtin___snprintf_chk' output between 9 and 17 bytes into a destination of size 9
|    67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
|       |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|    68 |        __bos (__s), __fmt, __va_arg_pack ());
|       |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| cc1plus: all warnings being treated as errors
`

### PR DESCRIPTION
**Pull request by priv-kweihmann**
GCC 10.x rightfully complains about out-of-bounds snprintf operation
on 64bit systems, where size_t could be 64bit sized.
Cast bytes_read down to 32bit and printf it without specifying input
format

Fixes #1461 

Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>

### CODE REVIEW

File: Release/src/http/common/http_helpers.cpp [hunk 1]
```diff
@@ -88,7 +88,7 @@ size_t chunked_encoding::add_chunked_delimiters(_Out_writes_(buffer_size) uint8_
 #ifdef _WIN32
         sprintf_s(buffer, sizeof(buffer), "%8IX", bytes_read);
 #else
-        snprintf(buffer, sizeof(buffer), "%8zX", bytes_read);
+        snprintf(buffer, sizeof(buffer), "%8X", (std::uint32_t)bytes_read);
```
Comment (BrandonStaab) [inline Release/src/http/common/http_helpers.cpp:91]: Why not use `static_cast` instead of the old c-style cast?

Comment (priv-kweihmann) [reply Release/src/http/common/http_helpers.cpp:91]: To me it looks like C-code (maybe because I'm a C guy) - but I have no strong opinion about it

Comment (priv-kweihmann) [reply Release/src/http/common/http_helpers.cpp:91]: @BrandonStaab ping

Comment (BrandonStaab) [reply Release/src/http/common/http_helpers.cpp:91]: I think a `static_cast` is more appropriate here since the old c-style cast has the potential to do much more, and potentially unwanted things.

Comment (priv-kweihmann) [reply Release/src/http/common/http_helpers.cpp]: Done

File: Release/src/http/common/http_helpers.cpp [hunk 2]
```diff
@@ -88,7 +88,7 @@ size_t chunked_encoding::add_chunked_delimiters(_Out_writes_(buffer_size) uint8_
 #ifdef _WIN32
         sprintf_s(buffer, sizeof(buffer), "%8IX", bytes_read);
 #else
-        snprintf(buffer, sizeof(buffer), "%8zX", bytes_read);
+        snprintf(buffer, sizeof(buffer), "%8X", static_cast<std::uint32_t>(bytes_read));
```
Comment (BrandonStaab) [inline Release/src/http/common/http_helpers.cpp:91]: Looks good to me

**Comment by priv-kweihmann** [comment]
@BrandonStaab  anything I can do to get this merged?

**Comment by priv-kweihmann** [comment]
@all is there anything I can do to get this here merged?

**Comment by Alexander-Degtyar** [comment]
Merge request helped me. (gcc 10.2.0)

**Comment by Hyask** [comment]
Any chances to see this merged and released?

**Comment by nlogozzo** [comment]
Trying to build on Arch via AUR and getting errors. Building with this PR fixes all issues...please merge and release

**Comment by priv-kweihmann** [comment]
Soon this PR will have its first anniversary - is there the slightest chance of getting it at least merged - I mean to me this is a critical bug, as without it even compilation is broken

**Comment by BrandonStaab** [comment]
@barcharcraz, can you give us some feedback on this as everyone using a modern compiler gets a compilation error without this PR

**Comment by keyonjie** [comment]
2 years passed, looks we have to carry this manually with ourselves.

**Comment by priv-kweihmann** [comment]
> 2 years passed, looks we have to carry this manually with ourselves.

Maybe time to drop this PR to increase the pressure :imp: :grin:

**Comment by priv-kweihmann** [comment]
@barcharcraz, as the other former maintainers are not responding to the merge this code change here, would you be willing to unblock the compilation for anyone with have gcc 10+?

**Comment by raholly** [comment]
It has been five years since this question was first raised.

**Comment by yuxiang-wen** [comment]
收到，谢谢
