### ISSUE TITLE
2.10.3 build failure on <= OS X 10.11 with <= Xcode 8.2.1

### ISSUE THREAD

**Issue by ilovezfs** [Microsoft/cpprestsdk#828]
```
[ 50%] Building CXX object src/CMakeFiles/cpprest.dir/uri/uri_builder.cpp.o
cd /tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/src && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DCPPREST_FORCE_HTTP_CLIENT_ASIO -DCPPREST_FORCE_HTTP_LISTENER_ASIO -Dcpprest_EXPORTS -I/tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/Release/include -I/tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/Release/src/pch -I/tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/Release/libs/websocketpp -I/usr/local/include -isystem /usr/local/opt/openssl/include  -stdlib=libc++ -Wno-return-type-c-linkage -Wno-unneeded-internal-declaration -std=c++11 -fno-strict-aliasing -DNDEBUG -fPIC   -Werror -pedantic -Wall -Wextra -Wcast-qual -Wconversion -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-format-attribute -Wmissing-include-dirs -Wpacked -Wredundant-decls -Wno-overloaded-virtual -Wno-sign-conversion -Wno-deprecated -Wno-unknown-pragmas -Wno-reorder -Wno-char-subscripts -Wno-switch -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value -Wno-unknown-warning-option -Wno-return-type-c-linkage -Wno-unused-function -Wno-sign-compare -Wno-shorten-64-to-32 -Wno-unused-local-typedefs -Wno-delete-non-virtual-dtor -Wno-unused-lambda-capture -o CMakeFiles/cpprest.dir/uri/uri_builder.cpp.o -c /tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/Release/src/uri/uri_builder.cpp
[ 53%] Building CXX object src/CMakeFiles/cpprest.dir/utilities/asyncrt_utils.cpp.o
cd /tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/src && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DCPPREST_FORCE_HTTP_CLIENT_ASIO -DCPPREST_FORCE_HTTP_LISTENER_ASIO -Dcpprest_EXPORTS -I/tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/Release/include -I/tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/Release/src/pch -I/tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/Release/libs/websocketpp -I/usr/local/include -isystem /usr/local/opt/openssl/include  -stdlib=libc++ -Wno-return-type-c-linkage -Wno-unneeded-internal-declaration -std=c++11 -fno-strict-aliasing -DNDEBUG -fPIC   -Werror -pedantic -Wall -Wextra -Wcast-qual -Wconversion -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-format-attribute -Wmissing-include-dirs -Wpacked -Wredundant-decls -Wno-overloaded-virtual -Wno-sign-conversion -Wno-deprecated -Wno-unknown-pragmas -Wno-reorder -Wno-char-subscripts -Wno-switch -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value -Wno-unknown-warning-option -Wno-return-type-c-linkage -Wno-unused-function -Wno-sign-compare -Wno-shorten-64-to-32 -Wno-unused-local-typedefs -Wno-delete-non-virtual-dtor -Wno-unused-lambda-capture -o CMakeFiles/cpprest.dir/utilities/asyncrt_utils.cpp.o -c /tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/Release/src/utilities/asyncrt_utils.cpp
/tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/Release/src/utilities/asyncrt_utils.cpp:54:32: error: default initialization of an object of const type 'const (anonymous namespace)::to_lower_ch_impl' without a user-provided default constructor
    constexpr to_lower_ch_impl to_lower_ch;
                               ^
                                          {}
/tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/Release/src/utilities/asyncrt_utils.cpp:65:32: error: default initialization of an object of const type 'const (anonymous namespace)::eq_lower_ch_impl' without a user-provided default constructor
    constexpr eq_lower_ch_impl eq_lower_ch;
                               ^
                                          {}
/tmp/cpprestsdk-20180806-90982-cgtnjd/cpprestsdk-2.10.3/Release/src/utilities/asyncrt_utils.cpp:76:32: error: default initialization of an object of const type 'const (anonymous namespace)::lt_lower_ch_impl' without a user-provided default constructor
    constexpr lt_lower_ch_impl lt_lower_ch;
                               ^
                                          {}
3 errors generated.
make[2]: *** [src/CMakeFiles/cpprest.dir/utilities/asyncrt_utils.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/cpprest.dir/all] Error 2
make: *** [all] Error 2
```
https://gist.github.com/ilovezfs/a2407f4b21b0eca4549850acc03556d2
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/28272/version=el_capitan/console

**Comment by yhslln** [comment]
i got this error too,and i have no idea to solve it

**Comment by ilovezfs** [comment]
Thanks for the fix @BillyONeal

**Comment by BillyONeal** [comment]
No problem. I wish Clang didn't complain about not initializing all 0 members of that empty struct :/

**Comment by ilovezfs** [comment]
@BillyONeal The issue doesn't affect newer versions of Xcode running on >= macOS 10.12 but Xcode 8.2.1 is the latest that runs on OS X 10.11, so it's just a question of when you want to formally cut off users from being able to build on <= 10.11.
