### ISSUE TITLE
Cannot build with Clang 21.1.8

### ISSUE THREAD

**Issue by DaemonArcfour** [Microsoft/cpprestsdk#1840]
```
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/memory:80:
/usr/bin/../lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/unique_ptr.h:90:16: error: invalid application of 'sizeof' to an incomplete type 'web::json::details::_Value'
   90 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/unique_ptr.h:398:4: note: in instantiation of member function 'std::default_delete<web::json::details::_Value>::operator()' requested here
  398 |           get_deleter()(std::move(__ptr));
      |           ^
/home/aleh/Projects/Nova/nova_desktop/build/Debug/_deps/cpprestsdk-src/Release/include/cpprest/json.h:742:14: note: in instantiation of member function 'std::unique_ptr<web::json::details::_Value>::~unique_ptr' requested here
  742 |     explicit value(std::unique_ptr<details::_Value> v) : m_value(std::move(v))
      |              ^
/home/aleh/Projects/Nova/nova_desktop/build/Debug/_deps/cpprestsdk-src/Release/include/cpprest/json.h:35:7: note: forward declaration of 'web::json::details::_Value'
   35 | class _Value;
      |       ^
1 error generated.
```

**Comment by yuxiang-wen** [comment]
收到，谢谢

**Comment by leakingmemory** [comment]
It has been an issue compiling with clang for a while. I think it used to be at least with using llvm's standard library. This had to be patched for FreeBSD ports like this (patches for two files, split):

https://github.com/freebsd/freebsd-ports/blob/main/devel/cpprestsdk/files/patch-include_cpprest_json.h
https://github.com/freebsd/freebsd-ports/blob/main/devel/cpprestsdk/files/patch-src_json_json.cpp

Introduced patches in FreeBSD with PR:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276187

If you apply those patches you might get past this issue. Unfortunately there are more issues with compiling and using cpprestsdk with clang/llvm.
