### ISSUE TITLE
Does not compile with Boost 1.66

### ISSUE THREAD

**Issue by hrantzsch** [Microsoft/cpprestsdk#654]
```
In file included from /data/cpprestsdk/Release/src/websockets/client/ws_client_wspp.cpp:19:0:
/data/cpprestsdk/Release/include/pplx/threadpool.h: In constructor 'crossplat::threadpool::threadpool(size_t)':
/data/cpprestsdk/Release/include/pplx/threadpool.h:70:59: error: conversion to 'int' from 'size_t {aka long unsigned int}' may alter its value [-Werror=conversion]
     threadpool(size_t num_threads) : m_service(num_threads) {}
```

In Boost 1.66 the interface of `asio::io_service` was changed so that the constructor now expects an `int` rather than a `size_t`. (In addition, `io_service` is now deprecated in favor of `io_context`.)

**Comment by ras0219-msft** [comment]
This bug should be now fixed in master; thanks for reporting!
