### PR TITLE
Enable HTTP Compression on Linux

### PR DESCRIPTION
**Pull request by lepierre**
HTTP-Compression is enabled for Linux Systems. All tests pass successfully on my local Ubuntu 18.04. Machine.
Updates #863.

### CODE REVIEW

**Comment by BillyONeal** [comment]
CI build reports non-spurious failures for apt/Ubuntu with this change:

2018-11-11T00:06:04.2712520Z [1;31m../Release/tests/functional/http/client/compression_tests.cpp:1322: error: Failure in compress_client_server: (rsp.content_ready().wait()) threw exception: Failed to decompress the response body FAILED

**Comment by epistor** [comment]
@BillyONeal, can you re-run the CI build now that you've merged #963?  It looks like that merge occurred later than this test run, and that error may be related.

**Comment by BillyONeal** [comment]
@epistor Sadly not :/

**Comment by lepierre** [comment]
I cannot reproduce the failure on Ubuntu 16.04. in my VM. @BillyONeal Possibly there is a configuration issue in the Ubuntu_1604_Apt Job? Why is that PPA used and is it necessary to downgrade packages?

**Comment by BillyONeal** [comment]
@lepierre The default Pipelines VMs come with a PPA for later versions of PHP. Unfortunately that PPA comes with OpenSSL 1.1.x -- but the version of Boost that comes with 16.04 (1.58) doesn't work with 1.1.x. So we need to nuke that PPA to go back to the system default answer of 1.0.x.

(More recent Boost works with 1.1.x just fine -- but the reason we want this to work is 16.04 is still what you get with a default Azure VM, and we want that to work)

**Comment by dfhljf** [comment]
> CI build reports non-spurious failures for apt/Ubuntu with this change:
> 
> 2018-11-11T00:06:04.2712520Z �[1;31m../Release/tests/functional/http/client/compression_tests.cpp:1322: error: Failure in compress_client_server: (rsp.content_ready().wait()) threw exception: Failed to decompress the response body FAILED
``` cpp
class gzip_decompressor : public zlib_decompressor_base
{
public:
    gzip_decompressor() : zlib_decompressor_base(16) // gzip auto-detect
    {
    }
};
```
change 16 to 31?
``` cpp
class gzip_decompressor : public zlib_decompressor_base
{
public:
    gzip_decompressor() : zlib_decompressor_base(31) // gzip auto-detect
    {
    }
};
```
