### ISSUE TITLE
The cpprestsdk does not compile with Visual Studio 15.9.5 ...

### ISSUE THREAD

**Issue by iamwired** [Microsoft/cpprestsdk#1018]
Hi,

The cpprestsdk does not compile on Windows with Visual Studio 15.9.5 :

`...\vcpkg\vcpkg\installed\x64-windows\include\cpprest\streams.h(1750): error C3861: '_parse_input': identifier not found`

There is a workaround (disable the conformance mode) but it's far from being ideal.

Thanks.

**Comment by garethsb-sony** [comment]
You don't say what version you're using but I suspect this is already fixed by https://github.com/Microsoft/cpprestsdk/commit/81442344caac03d307131069876c02018b5d34e8#diff-b7eab9bef3112812905d6b46f88b83c9

**Comment by iamwired** [comment]
Exact, sorry for that.
I am using the vcpkg version which is 2.10.2-1 atm. 
vcpkg upgrade doesn't propose me a newer version of the sdk?
