### ISSUE TITLE
Boost 1.70 issues

### ISSUE THREAD

**Issue by Naville** [microsoft/cpprestsdk#1141]
Just a follow-up on #1054 
This is indeed an issue on boost side (interface changes it seems), however, it doesn't look like they plan to revert/fix it anytime soon.

In the comment section they prompted a few potential solutions: https://github.com/boostorg/asio/commit/59066d80b26e

Can we merge them into cpprestsdk?

**Comment by scpeters** [comment]
I believe these failures are coming from websocketpp, which is included as a git submodule in the following folder:

* https://github.com/microsoft/cpprestsdk/tree/master/Release/libs

There is a potential fix in https://github.com/zaphoyd/websocketpp/pull/814

**Comment by BattyBlogger** [comment]
Was this issue ever fixed? I just installed everything according to the instructions on OSX and it does not build because of these issues.

**Comment by Naville** [comment]
@BattyBlogger afaik, nope. You have to install Boost1.69 and older from source instead of 70

**Comment by niclar** [comment]
the develop branch of websocketpp works with boost 1.71

**Comment by AlexanderPaniutin** [comment]
Fails for 1.72

`In file included from /Users/me/github/socket.io-client-cpp/src/sio_client.cpp:8:
In file included from /Users/me/github/socket.io-client-cpp/src/internal/sio_client_impl.h:29:
In file included from /Users/me/github/socket.io-client-cpp/lib/websocketpp/websocketpp/config/asio_no_tls_client.hpp:32:
In file included from /Users/me/github/socket.io-client-cpp/lib/websocketpp/websocketpp/transport/asio/endpoint.hpp:32:
In file included from /Users/me/github/socket.io-client-cpp/lib/websocketpp/websocketpp/transport/asio/connection.hpp:46:
In file included from /Users/me/boost_1_72_0/boost/asio.hpp:24:
In file included from /Users/me/boost_1_72_0/boost/asio/basic_datagram_socket.hpp:20:
In file included from /Users/me/boost_1_72_0/boost/asio/basic_socket.hpp:27:
In file included from /Users/me/boost_1_72_0/boost/asio/executor.hpp:338:
/Users/apaniutin/boost_1_72_0/boost/asio/impl/executor.hpp:194:15: error: no member named 'defer' in 'std::__1::reference_wrapper<boost::asio::io_context>'
    executor_.defer(BOOST_ASIO_MOVE_CAST(function)(f), allocator_);
    ~~~~~~~~~ ^
`
