### PR TITLE
Revert "libcpprestsdk: fix building as a static library (#1344)"

### LINKED ISSUE #1388: CMake config doesn't add needed libcrypto link dependency
Not sure about this one&hellip;

Summary: if I update websocketpp to `develop` to get cpprestsdk working with Boost 1.72, the CMake-based build doesn't handle the resulting dependency on libcrypto.

I have a single source file `main.cpp`:

~~~cpp
#include <cpprest/http_client.h>

int main() {
}
~~~

&hellip;and `CMakeLists.txt`:

~~~CMake
cmake_minimum_required( VERSION 3.7 )

project( main )

find_package( Boost 1.72 REQUIRED system )
find_package( cpprestsdk REQUIRED        )

add_executable       ( main main.cpp                                  )
target_link_libraries( main PRIVATE cpprestsdk::cpprest Boost::system )
~~~

<sup>(I include the `Boost::system` because of the issue described in #991)</sup>

Since I'm using Boost 1.72, I've checked-out the [zaphoyd/websocketpp](https://github.com/zaphoyd/websocketpp) repo in `Release/libs/websocketpp` to `develop` ([bc0dc57](https://github.com/zaphoyd/websocketpp/commit/bc0dc579a58424d6874f04f7e7b03eaae1f35d0f)) as advised on [this comment](https://github.com/microsoft/cpprestsdk/issues/1378#issuecomment-608446341) on #1378.

Now the build fails with:

~~~no-highlight
/usr/bin/ld: CMakeFiles/main.dir/main.cpp.o: undefined reference to symbol 'CONF_modules_unload@@OPENSSL_1_1_0'
//usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: cannot make progress due to previous errors.
~~~

&hellip;but succeeds if I add `-lcrypto`.

Since these files are only using cpprestsdk, I think cpprestsdk's CMake config (and/or the CMake config of its dependencies) should be dealing with this in CMake targets.

Thank you for all work on this library.

### PR DESCRIPTION
**Pull request by c72578**
This reverts commit cb7ca74e5f3bdbde363ed4ddb5655e76931397bd.

Issues concerning linking (#1388) and cross compiling (#1378) have
been reported.

- Fixes #1388

### CODE REVIEW

**Comment by c72578** [comment]
Info concerning CI:
- Ubuntu_1604_Apt failed as a consequence of:
```console
2020-04-28T06:56:23.8920413Z Updating packages lists
2020-04-28T06:56:31.5750923Z E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/xenial/main/binary-amd64/Packages  Writing more data than expected (47382 > 46563)
2020-04-28T06:56:31.5752568Z E: Some index files failed to download. They have been ignored, or old ones used instead.
2020-04-28T06:56:31.5764352Z Warning:  apt-get update failed for some reason
```
See: https://dev.azure.com/vclibs/cpprestsdk/_build/results?buildId=2801&view=logs&j=d9b78e16-10dd-5ec7-a702-819033c09298&t=fdc01949-00bb-50be-aac1-50983baf790f&l=943
- Windows_VS2019_x64:
```console
**** outside_tests:no_transfer_encoding_content_length FAILED ****
```
https://dev.azure.com/vclibs/cpprestsdk/_build/results?buildId=2801&view=logs&j=5d72d3a4-37a1-5685-94fb-38a4feb625a0&t=62f00f4f-a09b-595a-13a2-ebd1b705ca5b&l=1827
