### ISSUE TITLE
"multiple_https_requests_sync_scheduler" test fails (Unhandled exception: Scheduler is already initialized)

### ISSUE THREAD

**Issue by Malayka** [Microsoft/cpprestsdk#965]
Hi!
I'm recently building currently last release (2.10.7) with CMake and during run of tests after the build one test is failing:

> ...\Release\tests\functional\http\client\outside_tests.cpp(115): error: Failure in multiple_https_requests_sync_scheduler: Unhandled exception: Scheduler is already initialized FAILED
> Test case outside_tests:multiple_https_requests_sync_scheduler FAILED

I've found out that the failing test is new one, introduced in e5c6d8407fa2ff8ef0ae9bbfa2fe23fe0d7c0e45 - during the test it calls new `get_cpprestsdk_ambient_scheduler()` function, introduced in the same commit; 
the latter eventually calls `_pplx_g_sched.set_scheduler()`, which throws exception, if there already was nonempty scheduler - which the case in the test. So it looks like an issue for me :)

**Comment by BillyONeal** [comment]
Hmmm any idea why it would be passing in CI then? https://dev.azure.com/vclibs/cpprestsdk/_build/results?buildId=228&view=logs

**Comment by Malayka** [comment]
Sorry for long answer.

First, after little investigation I found out that I was wrong about exception from `_pplx_g_sched.set_scheduler()` from **pplx.cpp** file, because in Windows this file does not participate in build. Actually call of `set_cpprestsdk_ambient_scheduler(syncScheduler)` in the test leads to code
`void __cdecl set_cpprestsdk_ambient_scheduler(const std::shared_ptr<scheduler_interface>& _Scheduler)
{
    pplx::set_ambient_scheduler(_Scheduler);
}`
from **pplxwin.cpp** and the latter leads to 
`inline void set_ambient_scheduler(std::shared_ptr< ::Concurrency::scheduler_interface> _Scheduler)
{
    throw invalid_operation("Scheduler is already initialized");
}`
from **pplconcrt.h** from Visual Studio headers.

Second, the task "to build CppRestSdk" moved to my colleague for one reason, as he discovered the problem was because of used version of Visual Studio; he says that the test fails if one uses Visual Studio 2013 and the test passes in case of Visual Studio 2017.
So he locally added patch to **outside_tests.cpp** - he modified condition of including the test
from
`#if (defined(_MSC_VER) && (_MSC_VER >= 1800)) && !CPPREST_FORCE_PPLX`
to
`#if (defined(_MSC_VER) && (_MSC_VER >= 1910)) && !CPPREST_FORCE_PPLX`.
